In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.arange(4)
print(arr[0])

0


In [3]:
arr = np.arange(4).reshape(2,2)
print(arr[0])

[0 1]


In [4]:
print(arr[0][0])
print(arr[0, 0])

0
0


In [5]:
arr = np.arange(20).reshape(4,5)
print(arr[:2])
print(arr[:,:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a%b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 2 3]


In [7]:
high = [92700,92400,92100,94300,92300]
low = [90000,91100,91700,92100,90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [8]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 467100 458700]


In [9]:
data = [
        [92700,92400,92100,94300,92300]
        ,[90000,91100,91700,92100,90900]
        ]
arr = np.array(data)
print(arr[0]*3+arr[1]*2)

[458100 459400 459700 467100 458700]


In [10]:
weight = np.array([3,2]).reshape(2,1)
print((weight * arr).sum(axis=0))

[458100 459400 459700 467100 458700]


In [12]:
arr = np.array([10,20,30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[cond0 & cond1])

[20]


In [13]:
arr = np.array([10,20,30])
print(arr[(arr>10) & (arr<30)])

[20]


In [14]:
arr = np.array([10,20,30])
cond = arr>10
arr[cond] = 1
arr[~cond] = 0
print(arr)

[0 1 1]


In [16]:
arr = np.array([10,20,30])
arr = np.where( arr > 10,1,0)
print(arr)

[0 1 1]


In [18]:
lge = np.array([93000,82400,99100,81000,72300])
result = lge[lge <= 85000]
print(len(result))

3


In [25]:
arr = np.arange(8).reshape(4,2)
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
28
[12 16]
[ 1  5  9 13]


In [28]:
a = np.arange(4)
b = np.arange(4,8)
c = np.vstack([a,b])
d = np.hstack([a,b])
print(c,d)

[[0 1 2 3]
 [4 5 6 7]] [0 1 2 3 4 5 6 7]
