In [30]:
import numpy as np

### 1. 1D 배열 생성 및 정보 확인

- 길이가 10인 배열을 생성하고, 배열의 크기(shape), 차원(ndim), 데이터 타입(dtype), 전체 크기(nbytes)를 출력하세요.


In [31]:
a = [0,1,2,3,4,5,6,7,8,9]
data_array_a = np.array(a)

In [32]:
data_array_a.shape

(10,)

In [33]:
data_array_a.ndim

1

In [34]:
data_array_a.dtype

dtype('int64')

In [35]:
data_array_a.nbytes

80

### 2.특정 값으로 배열 생성

- 값이 5로 채워진 3x4 배열을 생성하세요.
- 0에서 50까지의 정수를 가지는 1D 배열을 생성하고, 그 배열을 5x10 형태로 재구성하세요.


In [36]:
five = [
        [5, 5, 5]
        ,[5, 5, 5]
        ,[5, 5, 5]
        ,[5, 5, 5]    
        ]
data_array_five = np.array(five)
data_array_five

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [82]:
array_1d = np.arange(1,51)
array_2d = array_1d.reshape((5,10))
array_2d


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### 3. 기본 연산

- 두 개의 2x2 배열 A = [[1, 2], [3, 4]]와 B = [[5, 6], [7, 8]]를 생성하고, 다음을 수행하세요:
- 행렬 덧셈
- 행렬 요소별 곱셈


In [37]:
A = [
    [1,2]
    ,[3,4]
    ]
data_array_A = np.array(A)

In [38]:
B = [
    [5,6]
    ,[7,8]
    ]
data_array_B = np.array(B)

In [39]:
data_array_A + data_array_B

array([[ 6,  8],
       [10, 12]])

In [40]:
data_array_A * data_array_B

array([[ 5, 12],
       [21, 32]])

### 4. 조건 필터링

- 배열 [1, 2, 3, 4, 5, 6, 7, 8, 9]에서 짝수만 선택하세요.
- 배열 [10, 20, 30, 40, 50]에서 30보다 큰 값을 모두 0으로 변경하세요.

In [41]:
first = [1, 2, 3, 4, 5, 6, 7, 8, 9]
cond_array_first = np.array(first)

In [42]:
cond_array_first[cond_array_first % 2 == 0]

array([2, 4, 6, 8])

In [43]:
second = [10, 20, 30, 40, 50]
cond_array_second = np.array(second)

In [44]:
cond_array_second[cond_array_second > 30] = 0
cond_array_second

array([10, 20, 30,  0,  0])

### 랜덤 값 생성 및 통계 계산

- 3x3 배열  임의 값 들어간 것을 생성하고, 배열의 최댓값, 최솟값, 평균, 표준 편차를 구하세요.
각 행의 최댓값, 최솟값, 평균, 합계를 구하세요.

In [46]:
random = [
        [1,2,3]
        ,[4,5,6]
        ,[7,8,9]
        ]
random_array = np.array(random)

In [47]:
random_array.max()

9

In [48]:
random_array.min()

1

In [49]:
random_array.mean()

5.0

In [50]:
random_array.std()

2.581988897471611

In [58]:
random_array_row = random_array.sum(axis=0)
random_array_row

array([12, 15, 18])

In [59]:
random_array_row.max()

18

In [62]:
random_array_row.min()

12

In [63]:
random_array_row.mean()

15.0

In [64]:
random_array_row.sum()

45

In [60]:
random_array_columns = random_array.sum(axis=1)
random_array_columns

array([ 6, 15, 24])

In [65]:
random_array_columns.max()

24

In [66]:
random_array_columns.min()

6

In [67]:
random_array_columns.mean()

15.0

In [68]:
random_array_columns.sum()

45

### 마스크 활용

- 5x5 배열을 생성하고, 배열에서 짝수 값만 선택하세요.


In [69]:
d_five = [
        [1,2,3,4,5]
        ,[6,7,8,9,10]
        ,[11,12,13,14,15]
        ,[16,17,18,19,20]
        ,[21,22,23,24,25]
        ]

d_five_array = np.array(d_five)

In [70]:
d_five_array[d_five_array % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

### 유니버설 함수 활용

- 배열 [1, 4, 9, 16, 25]의 각 요소에 대해 제곱근을 계산하세요.
- 배열 [1, 2, 3, 4]의 각 요소# 에 대해 exe^x 값을 계산하세요.

In [71]:
d_one = [1, 4, 9, 16, 25]
d_one_array = np.array(d_one)

In [75]:
d_one_array_sqrt = np.sqrt(d_one_array)
d_one_array_sqrt

array([1., 2., 3., 4., 5.])

In [77]:
d_two = [1, 2, 3, 4]
d_two_array = np.array(d_two)

In [78]:
d_two_array_exp = np.exp(d_two_array)
d_two_array_exp

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])