### 기본 사칙연산

In [1]:
import numpy as np

In [2]:
data_list_first = [1, 2, 3]
type(data_list_first), len(data_list_first)

(list, 3)

In [3]:
data_list_second = [4,5,6]

In [4]:
data_list_first + data_list_second

[1, 2, 3, 4, 5, 6]

In [5]:
data_list_third = [-1, 2, -3]

In [6]:
data_list_third * 2

[-1, 2, -3, -1, 2, -3]

#### array 연산

In [7]:
data_array_first = np.array(data_list_first)
type(data_array_first), len(data_array_first)

(numpy.ndarray, 3)

In [8]:
data_array_second = np.array(data_list_second)

In [9]:
data_array_first + data_array_second

array([5, 7, 9])

In [10]:
data_array_first / data_array_second

array([0.25, 0.4 , 0.5 ])

In [11]:
data_array_first * data_array_second

array([ 4, 10, 18])

In [12]:
data_array_third = np.array(data_list_third)
data_array_third

array([-1,  2, -3])

In [13]:
data_array_first - data_list_third, data_list_third - data_array_first

(array([2, 0, 6]), array([-2,  0, -6]))

### 브로드 캐스팅

In [14]:
data_array_third * 2  # [-2,  0, -6] * [2, 2, 2]

array([-2,  4, -6])

### 조건절 적용

In [15]:
cond_array_first = np.array([10, 20, 30])

In [16]:
conditions = cond_array_first > 10 # [10, 20, 30] > [10, 10, 10]
conditions

array([False,  True,  True])

In [17]:
cond_array_first[cond_array_first > 10]

array([20, 30])

In [18]:
conditions.all() # 구성 요소가 하나라도 False -> False

False

In [19]:
conditions_second = cond_array_second = np.array([20, 20, 30])
conditions_second = cond_array_second >= 20
conditions_second

array([ True,  True,  True])

In [20]:
conditions_second.all()

True

In [21]:
conditions_second.any() # 구성 요소 중 하나라도 True -> True

True

In [22]:
# [10, 20, 30] -> 10 초과, 30 미만
conditions_third = (cond_array_first > 10) & (cond_array_first < 30)
conditions_third

array([False,  True, False])

In [23]:
cond_array_first[conditions_third]

array([20])

### 집계함수

In [24]:
aggregation_list_first = [
                        [1,2]
                        ,[9,4]
                        ,[5,10]
                        ,[7,8]
                        ] # row4, col2

In [25]:
aggregation_array_first = np.array(aggregation_list_first)
aggregation_array_first

array([[ 1,  2],
       [ 9,  4],
       [ 5, 10],
       [ 7,  8]])

In [26]:
# aggregation_array_first.sum()
# aggregation_array_first.sum(axis=0) # 행 중심
aggregation_array_first.sum(axis=1) # 열 중심


array([ 3, 13, 15, 15])

#### max(), min(), mean()

In [27]:
# aggregation_array_first.max()
aggregation_array_first.max(axis = 0)

array([ 9, 10])

In [28]:
aggregation_array_first.argmax(axis = 0) # 위치 값을 나타냄

array([1, 2])

### 특수행렬 생성

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬 정보 확인

In [32]:
aggregation_array_first.shape # 차원 크기

(4, 2)

In [33]:
aggregation_array_first.ndim # 차원 수

2

In [34]:
aggregation_array_first.dtype

dtype('int64')

In [35]:
aggregation_array_first.size

8

In [36]:
aggregation_array_first.nbytes, aggregation_array_first.itemsize * aggregation_array_first.size # 요소에 전체 바이트 사이즈

(64, 64)

In [37]:
array_float = aggregation_array_first.astype(np.float128)

In [38]:
array_float.shape, array_float.dtype, array_float.nbytes # AI 에서 원자화 이용

((4, 2), dtype('float128'), 128)

### Merge
- stack(), concatenate()

In [39]:
merge_array_first = np.array([[1,2], [3,4]])
merge_array_second = np.array([[5,6], [7,8]])
merge_array_third = np.array([[10,11], [12,13], [14,15]])

In [40]:
merge_array_first.shape, merge_array_second.shape, merge_array_third.shape

((2, 2), (2, 2), (3, 2))

In [41]:
# 행 머지
np.concatenate((merge_array_second,merge_array_third), axis = 0)

array([[ 5,  6],
       [ 7,  8],
       [10, 11],
       [12, 13],
       [14, 15]])

In [42]:
# 열 머지
# np.concatenate((merge_array_second,merge_array_third), axis = 1) # error 행이 다르기 때문
np.concatenate((merge_array_second,merge_array_first), axis = 1)

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

### 차원 연산

In [45]:
# 벡터 연산 : dot product, 내적, inner product
# first = [3,4]
# second = [2,1]
first = [3,4,5]
second = [2,1,1]

array_first = np.array(first)
array_second = np.array(second)

dot_product_result = np.dot(array_first, array_second) # np.dot 넘파이에서의 dot_product 연산
dot_product_result, type(dot_product_result)

(15, numpy.int64)

In [48]:
array_first, type(array_first), array_first.shape, array_first.T.shape

(array([3, 4, 5]), numpy.ndarray, (3,), (3,))