### 기본 사칙연산

In [116]:
import numpy as np

In [117]:
data_list_first = [1, 2, 3]
type(data_list_first), len(data_list_first)

(list, 3)

In [118]:
data_list_second = [4,5,6]

In [119]:
data_list_first + data_list_second

[1, 2, 3, 4, 5, 6]

In [120]:
data_list_third = [-1, 2, -3]

In [121]:
data_list_third * 2

[-1, 2, -3, -1, 2, -3]

#### array 연산

In [122]:
data_array_first = np.array(data_list_first)
type(data_array_first), len(data_array_first)

(numpy.ndarray, 3)

In [123]:
data_array_second = np.array(data_list_second)

In [124]:
data_array_first + data_array_second

array([5, 7, 9])

In [125]:
data_array_first / data_array_second

array([0.25, 0.4 , 0.5 ])

In [126]:
data_array_first * data_array_second

array([ 4, 10, 18])

In [127]:
data_array_third = np.array(data_list_third)
data_array_third

array([-1,  2, -3])

In [128]:
data_array_first - data_list_third, data_list_third - data_array_first

(array([2, 0, 6]), array([-2,  0, -6]))

### 브로드 캐스팅

In [129]:
data_array_third * 2  # [-2,  0, -6] * [2, 2, 2]

array([-2,  4, -6])

### 조건절 적용

In [130]:
cond_array_first = np.array([10, 20, 30])

In [131]:
conditions = cond_array_first > 10 # [10, 20, 30] > [10, 10, 10]
conditions

array([False,  True,  True])

In [132]:
cond_array_first[cond_array_first > 10]

array([20, 30])

In [133]:
conditions.all() # 구성 요소가 하나라도 False -> False

False

In [134]:
conditions_second = cond_array_second = np.array([20, 20, 30])
conditions_second = cond_array_second >= 20
conditions_second

array([ True,  True,  True])

In [135]:
conditions_second.all()

True

In [136]:
conditions_second.any() # 구성 요소 중 하나라도 True -> True

True

In [137]:
# [10, 20, 30] -> 10 초과, 30 미만
conditions_third = (cond_array_first > 10) & (cond_array_first < 30)
conditions_third

array([False,  True, False])

In [138]:
cond_array_first[conditions_third]

array([20])

### 집계함수

In [139]:
aggregation_list_first = [
                        [1,2]
                        ,[9,4]
                        ,[5,10]
                        ,[7,8]
                        ] # row4, col2

In [140]:
aggregation_array_first = np.array(aggregation_list_first)
aggregation_array_first

array([[ 1,  2],
       [ 9,  4],
       [ 5, 10],
       [ 7,  8]])

In [141]:
# aggregation_array_first.sum()
# aggregation_array_first.sum(axis=0) # 행 중심
aggregation_array_first.sum(axis=1) # 열 중심


array([ 3, 13, 15, 15])

#### max(), min(), mean()

In [142]:
# aggregation_array_first.max()
aggregation_array_first.max(axis = 0)

array([ 9, 10])

In [143]:
aggregation_array_first.argmax(axis = 0) # 위치 값을 나타냄

array([1, 2])

### 특수행렬 생성

In [144]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [145]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [146]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬 정보 확인

In [147]:
aggregation_array_first.shape # 차원 크기

(4, 2)

In [148]:
aggregation_array_first.ndim # 차원 수

2

In [149]:
aggregation_array_first.dtype

dtype('int64')

In [150]:
aggregation_array_first.size

8

In [151]:
aggregation_array_first.nbytes, aggregation_array_first.itemsize * aggregation_array_first.size # 요소에 전체 바이트 사이즈

(64, 64)

In [152]:
array_float = aggregation_array_first.astype(np.float128)

In [153]:
array_float.shape, array_float.dtype, array_float.nbytes # AI 에서 원자화 이용

((4, 2), dtype('float128'), 128)